config/routes.rb
Rails.application.routes.draw do
   root :to => "homes#index"
   resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @books = Book.all
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      flash[:notice] = "create error"
      render action: :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.update(book_params)
       @book.save
      flash[:notice] = "Book was successfully updated."
      redirect_to action: :show
    else
      flash[:notice] = "update error"
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    if book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to action: :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  </ul>
  <% end %>
<% end %>

<%= form_with model: @book, local:true do |f| %>
  <div class ="field">
    <label for>Title</label>
    <%= f.text_field :title %></div>
  <div class ="field">
    <label for>Body</label>
    <%= f.text_area :body %></div>
  <div class ="actions">
    <%= f.submit 'Update Book' %></div>

<%= link_to "Show", book_path(@book.id) %>
 |
<%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Books</h1>
 <table>
   <thead>
     <th>Title</th>
     <th>Body</th>
     <th colspan="3"></th>
   </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>

  <form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="urNZp+dNVYd3KCWVoAgIRJ1z9hA0WLx3Jf5lZg376hKBMUtoOKj81+hc1bbqo86rewXzSRi3Nl4CxeIvRF8nFA==">

    <div class="field">
      <h2>New Book</h2>
      <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= @book.errors.count %>
        errors prohibited this book from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
        <%= message %></ul>
        <% end %>
      <% end %>
      </div>

      <%= form_with model: @book, local:true do |f| %>
        <div class="field_with_errors">
            <div class ="field">
            <label for>Title</label>
        </div>
            <%= f.text_field :title %></div>
        <div class="field_with_errors">
            <div class ="field">
            <label for>Body</label>
        </div>
          <%= f.text_area :body %></div>
        <div class ="actions">
          <%= f.submit 'Create Book' %></div>
      <% end %>
    </div>
  </form>

app/views/books/new.html.erb
<p id="notice"><%= notice %></p>
<h1>Books</h1>
 <table>
   <thead>
     <th>Title</th>
     <th>Body</th>
     <th colspan="3"></th>
   </thead>
  <tbody>
    <% @books .each do | book | %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>

<form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="authenticity_token" value="urNZp+dNVYd3KCWVoAgIRJ1z9hA0WLx3Jf5lZg376hKBMUtoOKj81+hc1bbqo86rewXzSRi3Nl4CxeIvRF8nFA==">

    <div class="field">
      <h2>New Book</h2>
      <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= @book.errors.count %>
        errors prohibited this book from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %></ul>
      <% end %>
      </div>

      <%= form_with model: @book, local:true do |f| %>
        <div class="field_with_errors">
            <div class ="field">
            <label for>Title</label></div>
            <%= f.text_field :title %>
        </div>
        <div class="field_with_errors">
            <div class ="field">
            <label for>Body</label></div>
          <%= f.text_area :body %>
        </div>
        <div class ="actions">
          <%= f.submit 'Create Book' %></div>
      <% end %>
    </div>
  </form>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %>
 |
<%= link_to "Back", books_path %>

app/views/homes/index.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>

<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<a>
<%= link_to "start", books_path  %></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= yield %>
  </body>
</html>